[build]

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"
ar = "arm-linux-gnueabihf-ar" # optional

# Pi 2/3/4
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-eabi-gcc"

[target.armv7a-none-eabi]
linker = "arm-none-eabi-gcc"
